
services:
  nginx:
    image: nginx-trainee5:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apache2
    networks:
      - trainee-network
  
  apache2:
    image: apache2-trainee5:latest
    networks:
      - trainee-network

networks:
  trainee-network:
    driver: bridge
